### ISSUE TITLE
crashing on start

### ISSUE THREAD

**Issue by DirtyNightmare** [prom3theu5/ConanExilesServerUpdater#10]
it crashing when i start it up not sure if i had changed the config right
```
{
  "Twitch": {
    "OAuth": null,
    "Username": null,
    "Channel": null
  },
  "Discord": {
    "DiscordToken": null,
    "ChannelId": 0
  },
  "Conan": {
    "FolderPath": "D:\SteamLibrary\Servers\conan",
    "Executable": "StartConanServer.bat",
    "StartupParameters": null
    "RaidingProtectionHoursEnabled": false,
    "RaidingStartHour": 0,
    "RaidingLengthInHours": 0,
    "AvatarsEnabledCertainHours": false,
    "AvatarActivationHour": 0,
    "AvatarsActiveLengthInHours": 0
  },
  "Update": {
    "ShouldInstallSteamCmdIfMissing": false,
    "ShouldInstallConanServerIfMissing": false,
    "SteamCmdPath": "D:\SteamLibrary\SteamCMD",
    "AnnounceDiscord": false,
    "AnnounceTwitch": false,
    "AnnounceMinutesBefore": 5,
    "UpdateCheckInterval": 5,
    "InstalledBuild": 0,
    "UpdateOnLaunch": false
  },
  "General": {
    "ShouldRestartConanOnNotRunning": true,
    "RestartServerAfterHours": 0
  }
}
```

**Comment by prom3theu5** [comment]
Hey there

You need to include double slashes in your folder paths, and trail it with a double slash, so like
`D:\\SteamLibrary\\SteamCMD\\`
instead of
`D:\SteamLibrary\SteamCMD`

and

`D:\\SteamLibrary\\Servers\\conan\\`
instead of 
`D:\SteamLibrary\Servers\\conan`

Also the executable is ConansandboxServer.exe, not your batch file
And you have to fill the StartupParameters with everything that usually goes in the batch file, like:

`"ConanSandBox?Multihome=%IP%?GameServerPort=%GamePort%?GameServerQueryPort=%QueryPort%?MaxPlayers=%MaxPlayers%?listen?AdminPassword=%AdminPass%"`

Where you replace the following:

%IP%,
%GamePort%,
%QueryPort%,
%MaxPlayers%
%AdminPass%

**Comment by DirtyNightmare** [comment]
start up parameter?
 what i use in my start up batch file is 
`start ConanSandboxServer.exe -log -QueryPort=27016` as all the other stuff is changed in the ini's
so it should be like
`"ConanSandBox?GameServerQueryPort=%27016%?"` what about the -log?

**Comment by prom3theu5** [comment]
Thats right - just have to remove those % marks

You don't have to worry about -log, it adds it automatically :)
