### ISSUE TITLE
I cant create a service

### ISSUE THREAD

**Issue by C0kkie** [prom3theu5/ConanExilesServerUpdater#14]
Hello,

if i want to use the command ConanExilesUpdater.exe install
and after i entered the username and the password i get the error

Während der Installationsphase ist eine Ausnahme aufgetreten.
System.ComponentModel.Win32Exception: Der Kontoname ist unzulässig oder
rhanden, oder das Kennwort ist für den angegebenen Kontennamen ungültig

i tried it multiple times

**Comment by prom3theu5** [comment]
Because it's a service installation you also have to specify Domain.
If you aren't part of a domain, enter the username with a .\ at the start of it, so: `.\user` not just `user` :)

Also - be sure you are running the latest release, as the earlier one had an issue with the config.json location when running as a service - thats all fixed now :)

**Comment by prom3theu5** [comment]
Also - you don't have to run it as a service, you can just double click it and it'll run as a console app.
If you run it as a service, both this app, and the conan server will run headless, meaning you can see them running in task manager, and everything will work fine, but you won't see any open windows :)
