### ISSUE TITLE
Raids/AvatarHours and double-quotes issues with parsing

### ISSUE THREAD

**Issue by Slympp** [prom3theu5/ConanExilesServerUpdater#16]
Hey, I'm trying to make the updater working with Raids/AvatarHours ; the .ini files are correctly updated when needed, but changes are not applied in game. Does the server need to restart everytime that one of these settings are turned on/off ?

Also, I've figurated that your parser remove double-quotes in .ini files which occurs issues with double-quoted strings (i.e. ServerName in Engine.ini). For example, if I run the updater with theses parameters in Engine.ini:

ServerName="NameOfServer | Foo | Bar", the server name will be correct, but at next restart the double-quotes are removed and the line change to "ServerName=NameOfServer" because pipes are no longer escaped and the text is cutted.

Sorry for my english it's not my native language, and congrats for your updater, code is nice and I've learned new things :)

**Comment by prom3theu5** [comment]
Your english si fine - don't worry :)

In Json you will have to escape those quotes, so add a \ before each one. I.e.
`ServerName=\"NameOfServer | Foo | Bar\"`

I think you are right about the in game changes requiring a reboot.
I was under the impression that because an admin can change the settings on the fly inside the game when logged in, that the server periodically checked the server file. I guess I was wrong.

I could add an auto restart in for those

**Comment by Slympp** [comment]
An additional configurablerable auto restart would be great

**Comment by sirchojin** [comment]
+1.

I guess you can modify live parameters when you are using client and because you are connected to the game server.
But without any client, it is impossible to modify parameters without having server restart.

So auto-restart (like you do when funcom patch is live) when it is time to change raid option is the best solution for now.

**Comment by DirtyNightmare** [comment]
@gpoudrel you are right you can change the params in the ini when the server is live but some of them only do take effect after a restart thoose settings that requires a restart is thoose that are greyed out in the server setting ingame like(pvp enabled)

**Comment by prom3theu5** [comment]
This is sorted int he latest version, after changing the ini files- it will force close the server, and then as long as you have auto restarts enabled - start it back up again with the new config loaded
