### ISSUE TITLE
Server auto restart not accepting configuration value

### ISSUE THREAD

**Issue by Aoxmodeus** [prom3theu5/ConanExilesServerUpdater#3]
If I configure the server updater to autorestart, at any interval specified, always restarts at 5 minutes.

Here is the Discord channel output:

Conan Server Automatic Restarts are set to run every 6 Hours. The server has been up for 0.113783944444444 H 6 M. The Server will restart in 5 Minutes.

Disabling auto restart is the only option.  Works fine though, every 5 minutes :)

**Comment by prom3theu5** [comment]
Auto restart of the server is fixed in the latest release
[New Release](https://github.com/prom3theu5/ConanExilesServerUpdater/releases/download/1.3/1.3.zip)

Also offers auto download of both steamcmd and the conan server.

Not sure about the interval - you definitely have the restart value set. Perhaps a timezone issue?

**Comment by prom3theu5** [comment]
no - Scratch that, my mistake.
New version uploading in a few minutes - Also includes raiding protections on buildings, with allowed raiding times (can be disabled)
